version: '3.8'

services:
  bookdlbot:
    image: bookdl
    container_name: bookdlbot
    build:
      context: https://github.com/Samfun75/BookdlBot.git
    restart: always
    env_file:
        - docker-config.ini
